### PR TITLE
Fixed the issue with the lines not wrapping

### PR DESCRIPTION
**Pull request by WDWaleed**
## Specified fix width for the box to make the lines wrap properly. Edited the code for other improvements as well.

Explanation: The problem was that you didn't specify explicit width for the .box element and therefore the h1 element was not wrapping. Also there was some code that was either not needed or too complicated so I simplified it to reduce the bundle size.
If you have any questions, don't hesitate to ask :)
Below is a screenshot of how the app look like now:
Screenshot 2023-09-05 at 20-00-24 Frontend Mentor QR code component

### CODE REVIEW

**Comment by WDWaleed** [comment]
Hi, 
please review the pull request and let me know what you think.

**Comment by mnyon-grandkru** [comment]
Hi Muhammad,

Thanks for the PR. This is a learning exercise, so let me learn from this and apply those lessons. Thanks so much for reaching out.

**Comment by WDWaleed** [comment]
Glad I could help but does this mean you aren't going to merge the PR? If so, then please let me know so that I can close it.

**Comment by mnyon-grandkru** [comment]
I'll merge it this week. If that's not a quick enough response for you, feel free to close it. Thanks.

**Review by mnyon-grandkru — APPROVED** [review]

**Pull request merged**
